# Generated by Django 4.1.7 on 2023-09-09 17:56

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_author_alter_post_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='main/images/images.jpg', null=True, upload_to=main.utils.post_directory_path),
        ),
    ]
