# Generated by Django 4.1.7 on 2023-09-28 13:51

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=main.utils.post_directory_path),
        ),
    ]
