# Generated by Django 5.0.6 on 2024-07-08 17:11

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comments_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='main\\static\\main\\images\x0ceatured-1.png', upload_to=main.utils.post_directory_path),
        ),
    ]
