# Generated by Django 4.1.7 on 2023-08-25 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
