# Generated by Django 4.1.7 on 2023-09-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
