# Generated by Django 4.1.7 on 2023-10-15 14:43

from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='media\\id_18fb1a27-ba96-4e74-8bfe-b69beb47f2a9\x0ceatured-5.png', null=True, upload_to=user.utils.user_directory_path),
        ),
    ]
