# Generated by Django 5.0.6 on 2024-07-09 15:35

import user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='/wuthering.jpg', null=True, upload_to=user.utils.user_directory_path),
        ),
    ]
